/**
 * Secret names declared in rayfin.yml.
 *
 * AUTO-GENERATED — do not edit manually.
 * Regenerated by `rayfin secret set`, `rayfin secret delete`, and whenever
 * function types are generated.
 *
 * This file augments the SDK's `RayfinSecretRegistry`, which is what types
 * `ctx.Secrets` in every function:
 *
 *   udf.func('charge', async (ctx: RayfinContext<AppSchema>) => {
 *     ctx.Secrets.MY_SECRET;   // string
 *     ctx.Secrets.NOT_THERE;   // compile error
 *   });
 *
 * Nothing imports this file — it only needs to be part of the compilation,
 * which the functions tsconfig's `src` include already guarantees.
 *
 * Only names appear here. Secret values are supplied per invocation and are
 * never written to disk.
 */

declare module '@microsoft/fabric-user-data-functions' {
  interface RayfinSecretRegistry {
    ONELAKE_FILES_URL: string;
  }
}

export {};
